name: mood_diary_evo_test
description: "Test work for EVO Mobile"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  get_it: ^9.2.0
  google_fonts: ^8.0.0
  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.1.0
  json_annotation: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.4
  build_runner: ^2.10.5
  freezed: ^3.2.4
  json_serializable: ^6.12.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons
    - assets/images